### ISSUE TITLE
Form Events and Compatibility with upcoming release Igor

### ISSUE THREAD

**Issue by splitbrain** [ComboStrap/combo#14]
This plugin seems to make use of one or more form related action events that will be removed in the next DokuWiki release. Please have a look at https://www.patreon.com/posts/better-forms-58551930 for details.

My apologies if this has already been addressed in your code. If you have any questions on how to implement the needed changes please let me know.

**Comment by gerardnico** [comment]
Thanks. I will look into it.

Just posting a link to the forum.

https://forum.dokuwiki.org/d/19733-please-check-if-your-plugin-uses-obsolete-form-events/1

Success

**Comment by gerardnico** [comment]
I just have make the code ready to receive the new release.
https://github.com/ComboStrap/combo/commit/ff25c0778a6dfa7f2c8b2cafc67a22e5ff8015d8

Succes !
