### ISSUE TITLE
DW styling gone completely

### ISSUE THREAD

**Issue by iainhallam** [ComboStrap/combo#21]
I've enable Combo, Strap, and the Combo renderer. All well and good, but things that rely on DokuWiki's styles, such as the Admin page, and tabs in Extension Manager, simply render as bulleted lists. Is there something I'm missing, or are these meant to be changed? It's quite a usability issue not having the styles at all.

**Comment by gerardnico** [comment]
Hallo and happe new week.

You are right. The historical reasons are multiple.
* Conflict: There was conflict with Bootstrap
* Performance: The Css used comes in one big bundle on every page even if you don't use them.
* Lack of knowledge: it was difficult to tell where the css was used. They were therefore deleted and added back if needed.

As of today, we get a css modular system and if you want to add some css for this page, we will happily add it.

**Comment by gerardnico** [comment]
We have added a basic stylesheet for the admin page:
https://github.com/ComboStrap/dokuwiki-template-strap/blob/main/css/admin.css

If you want it adjusted, you can change it or ask it with the new css rule properties. 

Feel free to answer or continue the conversation.

**Comment by gerardnico** [comment]
Ok. It's split in two, unfortunately, there is also some css here:
https://github.com/ComboStrap/combo/blob/4cadd4f8c541149bdda95f080e38a6d4e3a640ca/action/docss.php#L43
To support the [branding colors](https://combostrap.com/app/branding-colors-primary-secondary-adekm076). 
Next release, we will merge them.
