### ISSUE TITLE
Cannot Save in dokuwiki configuration manager

### ISSUE THREAD

**Issue by cuttherug** [ComboStrap/combo#24]
After installing combo through the dokuwiki extension manager I get a "403 Forbidden. Access to this resource on the server is denied!" error when trying to save in dokuwiki's 'configuration manager'.

I made sure I don't have any conflicting plugins installed. Is there anything else you think might be causing the error?

I'm on PHP 7.4

**Comment by gerardnico** [comment]
How did you get this feedback ?

A 403 is mostly due to bad permissions on the file system, which is weird.

**Comment by gerardnico** [comment]
We have actually solved a memory problem (not yet released) on admin page that was caused by a low memory setting on the server. If you don't use the strap template when saving, does it work ?

**Comment by gerardnico** [comment]
Do you have any bootstrap related plugin enabled ? (bootstrap3, ...)

**Comment by gerardnico** [comment]
I took a look in the [admin config manager plugin](https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/config/admin.php#L36) and there is no ACL check. Not sure why you get this 403. 
You can see the configuration admin page ?

**Comment by cuttherug** [comment]
I uninstalled bootstrap3 template and disabled bootstrap wrapper and I still get the issue.

Yes, I can see the page, but when I hit save I get the 403 issue.

**Comment by gerardnico** [comment]
Can I get temporary access to the wiki ?

I don't see how you can get a 403 on save. It's not even in the code.

How do you see that you get a 403 ?

**Comment by gerardnico** [comment]
For any credentials: support@combostrap.com
Not on this thread

**Comment by gerardnico** [comment]
The last version has just been released.
https://combostrap.com/release/1.24

We got no news, if there is still a problem, open an issue.

The release is not yet fully published on Dokuwiki because we have key website that needs to run with it for a couple of days but it has passed all test.
