### ISSUE TITLE
Multiple security alerts by Github dependabot

### ISSUE THREAD

**Issue by haneef95** [ComboStrap/combo#28]
Hi,

Github's dependabot is throwing multiple issues, could you check and fix them please?

They all seem to be in relation to upstream packages, which have since been fixed in newer versions.

![image](https://user-images.githubusercontent.com/298208/160296632-db83ba75-d588-4dc0-96df-56a8a5f8d273.png)

Since this repo is also on Github, you could potentially enable dependabot to get more info on those alerts.

Thank you,

**Comment by haneef95** [comment]
Details available here: https://github.com/haneef95/ComboStrap-combo/security/dependabot

You could check the pull-requests in that repo for details as well.

**Comment by haneef95** [comment]
The pull requests here have some more info: https://github.com/haneef95/ComboStrap-combo/pulls

**Comment by gerardnico** [comment]
thanks for the feedback. I will take a closer look tomorrow.

The JavaScript library in itself doesn't use any of this.

It seems that they are only dev dependency to create the build.
(Postcss, ...).

**Comment by gerardnico** [comment]
I have followed the [quick documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates):
https://github.com/ComboStrap/combo/blob/1.25/.github/dependabot.yml

We will see. Thanks !
