### ISSUE TITLE
Problem linking to files

### ISSUE THREAD

**Issue by listerr** [ComboStrap/combo#40]
Hello,

I am having a problem linking to files uploaded with media manager, e.g. pdf files:

`{{ :summary-of-rights_2020_v2.pdf |}}`

or a full path name: 

`{{:documents:summary-of-rights_2020_v2.pdf |}}`

The text of the link is displayed but the link is not rendered.

If I disable the combo extension, DW links to the file correctly.

I also tried this workaround:

`[[this>path/to/file.pdf]] `

Which produces a clickable link, but gets the error that it can't find the file and redirects to the search page, e.g.

> The page (:documents:summary-of-rights_2020_v2.pdf) doesn't exist. You have been redirected automatically to the search engine.

I've checked that the ACL is okay and tested from public pages, so I don't think it's an access issue. No 404s etc in the server logs, and if I turn off Combo plugin it seems to work okay.

-  DokuWiki 2022-07-31 "Igor"
-  Combo:  https://github.com/ComboStrap/combo/archive/refs/heads/1.24.1.zip

Rob

**Comment by gerardnico** [comment]
Sorry for that.

Can i have the HTML rendered ?

I made a test and it works for me.
```html
<a href="/lib/exe/fetch.php?media=mail.pdf" class="media mediafile mf_pdf" title="mail.pdf (768&nbsp;B)">mail.pdf</a>
```

We take over only image. See:
https://github.com/ComboStrap/combo/blob/main/syntax/media.php#L235
the rest goes through dokuwiki.

We are not testing yet on igor.

**Comment by listerr** [comment]
Okay.

Doesn't seem to try to link it at all. If I put it on a line by itself, I get:

From:

`{{document.pdf}}`

```html
<p>

document.pdf

</p>
```

If I put a link description, then just the description appears:

`{{document.pdf|Download PDF}}`

```html
<p>

Download PDF

</p>
```

I tried in a table, but is the same but no "<p>" tags, just unlinked text.

**Comment by gerardnico** [comment]
I'm  pulling out igor to check.

**Comment by listerr** [comment]
> We are not testing yet on igor.

Hmm okay. I had not realised that!

I followed the instructions at https://combostrap.com/get-started/how-to-install-dokuwiki-h52gxusb

> If you have already a Dokuwiki Installation, you should have the last version. We support the previous version only a couple of month.

and:

> If you don't have the last version, we recommend to install the [Upgrade plugin](https://www.dokuwiki.org/plugin:upgrade) and to **upgrade your installation**.

It is a little unclear on this page that you mean it _only_ works with Release 2020-07-29 "Hogfather" (and not previous release of that) and is not expected to work on Igor yet. :)

(Perhaps I understood "last version" to mean "latest version")

Rob

**Comment by gerardnico** [comment]
I'm testing the patch branch against igor.
Igor was released during the holidays making it difficult to follows along.

**Comment by listerr** [comment]
> Can you [disable it](https://combostrap.com/content/how-to-use-the-image-tag-in-combostrap-yy0sap72#imageenable) to see if it persists.

Yes. Disabling `imageEnable` fixes this!

I noticed I had set `defaultImageLinking`  to `nolink`, as I never really want _images_ to be clickable unless explicitly set.

I changed it back to `direct` and now the .pdf links work, even with `imageEnable` enabled.

**Comment by gerardnico** [comment]
Checking that. 
```
I noticed I had set defaultImageLinking to nolink
```

**Comment by gerardnico** [comment]
Man this is it. I'm on it.

**Comment by gerardnico** [comment]
The bug is the 'nolink' is passed to dokuwiki even if they are not image. And it works pretty well, unfortunately.

**Comment by gerardnico** [comment]
The last commit resolve this issue. You can get it by installing the [patch branch](https://github.com/ComboStrap/combo/archive/refs/heads/1.24.1.zip) manually.

I close it, open it again if it does not resolve your issue.

Well spotted !
