### ISSUE TITLE
A message to upgrade combo extension right after upgrading it

### ISSUE THREAD

**Issue by smmsadrnezh** [ComboStrap/combo#42]
After upgrading the combo extension, I'm getting a message to upgrade on top of all pages. You might see it in the following screenshot:

![message](https://user-images.githubusercontent.com/712956/187097783-3d9f5aa5-7503-41ea-b1eb-a84b4005e419.png)

Thanks for your excellent job on this awesome extension.

**Comment by smmsadrnezh** [comment]
It gets fixed after upgrading the template. You may close the issue.

**Comment by gerardnico** [comment]
Yeah that's annoying. 

I found it also annoying.  dokuwiki does not have an easy way to share code and I need to be sure that no one gets hurt when upgradind.

The next release get rid of the template. Much easier.

Have a nice day
