### ISSUE TITLE
require_once() causes Exception with symbolic links

### ISSUE THREAD

**Issue by J4MMlE** [ComboStrap/combo#43]
I get the following error:
`require_once(): Failed opening required '/some/other/path/to/lib/plugins/combo/ComboStrap/../../../../inc/search.php' (include_path='.:/opt/php/lib/php') /path/to/lib/plugins/combo/ComboStrap/FsWikiUtility.php(53)`

The `/path/to/lib/plugins` folder is symbolically linked to `/some/other/path/to/lib/plugins` so that `__DIR__` resolves to `/some/other/path/to/lib/plugins` instead of `/path/to/lib/plugins`. In this case `__DIR__` should not resolve the symbolic link.

**Comment by gerardnico** [comment]
Solved. Just update combo, your problem should disappear.

Thanks for reporting. Well spotted !
