### ISSUE TITLE
login page style not rendered by combostrap

### ISSUE THREAD

**Issue by baudryj** [ComboStrap/combo#44]
Hi,
after upgrading combostrap + strap theme
My login page style is not what is expected (with combo style)

![Capture du 2022-09-23 10-28-50](https://user-images.githubusercontent.com/259649/191921308-5a38d05b-d6f3-4738-8342-0fbc5d1be0fa.png)

any solution ?
(option is checked in admin panel)

**Comment by gerardnico** [comment]
Yeah, you are right. They have introduced a new forms system and I need to do it all again.

See the [igor release](https://www.dokuwiki.org/changes#release_2022-07-31a_igor)

```
New form events used. :!: Plugins should implement them, because the old form events are not triggered anymore
```

That's a lot of work that I don't have for now. I have just made it compatible to not break anything.

**Comment by gerardnico** [comment]
See https://github.com/ComboStrap/combo/issues/14 for more details. This is the preparation for the next release.
There is almost 6 forms to redo. https://github.com/ComboStrap/combo/commit/ff25c0778a6dfa7f2c8b2cafc67a22e5ff8015d8

**Comment by baudryj** [comment]
Ok, thanks ;-)
I will check it and see if I can contribute

Thanks a lot you did a very good job !

**Comment by gerardnico** [comment]
Thanks for the good words.

if I can find some time, I will try to do the login form.

The task is big but if i break it ... may be that I can find a time slot

**Comment by baudryj** [comment]
thanks !
(yep definitely login form first ;-) )

**Comment by gerardnico** [comment]
I don't see the why of this change, that's almost worst but I got finally some result.

![image](https://user-images.githubusercontent.com/2324340/191976206-18188146-121d-4419-b40e-c9126c0d43fd.png)

**Comment by gerardnico** [comment]
Done for the login. You just need to update the plugin. The code has been updated but not the version.
Hopefully, I didn't break anything.

Can you do an update and tell me if this is good for you ?
It works on my side.

**Comment by baudryj** [comment]
It works ;-) My 2ndbrain login page looks good !!
I re-install combo plugin (no update available)
Great Job !
![Capture du 2022-09-25 14-10-53](https://user-images.githubusercontent.com/259649/192142729-aa2937e0-e544-428a-866f-c70eac04c21f.png)

**Comment by baudryj** [comment]
C'est pour mon site perso dans mon labo (en construction).
Objectif : j'utilise et je veux généraliser l'utilisation de dokuwiki avec combostrap dans le labo
Use case : page perso / site projets / doc projet
Pourquoi : j'ai pas envie d'avoir plusieurs outils à gérer et en général les besoins sont simples ... les sites bougent peu
Combostrap permet de s'adapter à différents usages donc c'est bon pour moi !!
Je pourrais te communiquer les résultats d'ici un mois !

**Comment by gerardnico** [comment]
Dans la derniere version, les app forms ont ete mis a jour.

C'est une grosse release, il y a des etapes manuelles a realiser.
https://combostrap.com/release/release-1-25-layout-all-the-way-l17jxp17

Bonne soiree
Nico
