### ISSUE TITLE
Probleme with json-ld

### ISSUE THREAD

**Issue by baudryj** [ComboStrap/combo#45]
Hi,

When I change json-id I can't open metadata manager (I have to delete the page).

Error in console :
![Capture du 2022-11-07 16-43-42](https://user-images.githubusercontent.com/259649/200352665-d14f0f8a-f012-471a-b360-9fda7a4733c5.png)

Any idea ?

thanks
Julien

**Comment by gerardnico** [comment]
Or it can also be a problem when sending the metadata.
(they should be escaped, may be i miss something).

I need:
- of the new value
- of the json (it is visible in the browser devtool (f12) > Network. Refresh the page (f5), open the meta manager and you should see the network call with the json in the response tab)

**Comment by baudryj** [comment]
mistake -> (not json-id but json-ld)
when I put a value in the Json-Ld field (metadata manager)

![Capture du 2022-11-07 19-13-16](https://user-images.githubusercontent.com/259649/200384533-5f13c386-adc7-4600-b235-a0597de256dd.png)

I can't re-open the metadata manager.

for example with this value : 
{
"url":"https://www.yahoo.fr"
}

![Capture du 2022-11-07 19-24-41](https://user-images.githubusercontent.com/259649/200386480-63ccf1b8-904b-41a4-bc42-f2b6e504ff28.png)

I get this : 
`"json-ld": {
			"name": "json-ld",
			"label": "Json-ld",
			"type": "json",
			"url": "https:\/\/combostrap.com\/google",
			"description": "Advanced Page metadata definition with the json-ld format",
			"tab": "type",
			"value": {
				"url": "https:\/\/www.yahoo.fr"
			},
			"default": "{\n    \"@context\": \"https:\/\/schema.org\",\n    \"@type\": \"Article\",\n    \"url\": \"https:\/\/demo.databeam.eu\/batiphys\/metadata\/test2\",\n    \"headline\": \"Titre de niveau 1\",\n    \"datePublished\": \"2022-11-07T18:12:42+00:00\",\n    \"dateModified\": \"2022-11-07T18:12:42+00:00\",\n    \"publisher\": {\n        \"@type\": \"Organization\",\n        \"name\": \"Batiphys\"\n    },\n    \"speakable\": {\n        \"@type\": \"SpeakableSpecification\",\n        \"xpath\": [\n            \"\/html\/head\/title\"\n        ]\n    }\n}",
			"mutable": true
		}`

Can we use any metadata or not ?

**Comment by gerardnico** [comment]
Looking at it. Thanks for the data. Sorry for the inconvenience

**Comment by gerardnico** [comment]
It's the javascript library. We can see the value in the json. The library thinks that this is a string. Looking at it.

![image](https://user-images.githubusercontent.com/2324340/200512895-bb0bdcd0-c570-456e-ba2e-ebf9aa24a7d8.png)

**Comment by gerardnico** [comment]
Great website !

I was looking around and I saw your form.
https://demo.databeam.eu/batiphys/form/contact 
In a large screen, you got a large form.
If you want to have it constraint on width, you can use the [median layout](https://combostrap.com/layout/dynamic-layout-z9tl87hg#median). 

For json-ld, the documentation is [here](https://combostrap.com/social/google-rich-result-1os9d45q#json-ld)
You can validate it with this [website](https://json-ld.org/playground/)
We need to do better on metadata by page type.

**Comment by baudryj** [comment]
Thanks for median layout ;-) done
Combo is great ;-)

Here is the process :
1/ Create a page
2/ Edit metadata with metadata manager
3/ Paste the code below in json-ld field
`
{
  "@context": "https://schema.org",
  "@type": "Course",
  "name": "Introduction to Computer Science and Programming",
  "description": "Introductory CS course laying out the basics.",
  "provider": {
    "@type": "Organization",
    "name": "University of Technology - Eureka",
    "sameAs": "http://www.ut-eureka.edu"
  }
}
`
4/ Submit
5/ Impossible to open metadata manager
![Capture du 2022-11-08 12-21-03](https://user-images.githubusercontent.com/259649/200551919-e6d8ca87-e2eb-46c2-93c6-af9da3847c92.png)

![Capture du 2022-11-08 12-29-16](https://user-images.githubusercontent.com/259649/200554043-4e880e98-df2d-4f28-bb5e-89bc67e9aade.png)

You can check this page : https://demo.databeam.eu/batiphys/metadata/test3

**Comment by gerardnico** [comment]
It works for me after an update of combo.

I can't access the metadata manager of your page. 
![image](https://user-images.githubusercontent.com/2324340/200556865-6374f5c6-18e7-4c26-bfb1-214813f0c43e.png)

You can try it here:
https://combostrap.com/test-page-for-metadata-json-ld-3ahne79v

You can test it yourself also. I have open the page.

**Comment by baudryj** [comment]
It's Ok !
thanks !!
(but : website is down)
