### ISSUE TITLE
Images not loading because HTML code does not use https

### ISSUE THREAD

**Issue by arjay54** [ComboStrap/combo#47]
I have setup the page according to the instruction on the ComboStrap page.

Images do not load with option plugin»combo»imageEnable activated. When turning off images render correctly.

Images no loading with imageEnable activated:
![grafik](https://user-images.githubusercontent.com/79190983/201886684-200daf2e-597b-4400-9370-bc90c40070a5.png)

**Comment by gerardnico** [comment]
There is a content security policy that blocks your image.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Do you know which one it's ?


We don't allow mixed content. (HTTPS and http)
You can try by deleting this file

combo/action/metacsp.php

**Comment by arjay54** [comment]
I guess it is the mix of https with http. 
We use https for our wiki. Why does Combo insert the image links as http?

**Comment by gerardnico** [comment]
We follow Dokuwiki configuration https://www.dokuwiki.org/config:baseurl
If there is a value in this field, we take it.
No value in this field is the best value.

Do you have any value ?
such as http://....

**Comment by arjay54** [comment]
The field was originally left blank.

I have now entered the baseurl with https://www.****.wiki. This solved the problem. Images now render correctly.

**Comment by gerardnico** [comment]
Top.

That's still strange that dokuwiki is seeing http and not https.

Have a nice avond, arjay.
