### ISSUE TITLE
Too many redirects for userwrite=DokuWiki Internal

### ISSUE THREAD

**Issue by bpaddock** [ComboStrap/combo#50]
I am bring up a new DokuWiki, along side one that is running fine.

With both DokuWiki Igor and the 2022-Dec-29 snapshot when combo is installed and enabled,
and enabling Use nice URLs via:

userwrite=DokuWiki Internal

 things break in odd ways.

How it breaks depends on the browser.  
It may say that cookies are disabled (they aren't).
It may say there are too many redirects.

The only plugins installed are:
sqlite
strap
combo

The only configuration done is setting the above in the configuration manager.

The version of combo that is installed is what is currently installed by the extension manager.
Last updated on 2022-08-27

To recreate bring up a new DokuWiki. Create a 'start' page and another page, lets calling 'otherpage'.
With userwrite=none swapping between 'start' and 'otherpage' work fine.

With userwrite=DokuWiki Internal

trying to navigate to 'otherpage' from 'start' breaks with a cookie or redirect error.

This does not happen when combo is disabled.

**Comment by gerardnico** [comment]
Thanks for reporting. Sorry for the late answer, I got the flu.

I'm not really sure if we support the dokuwiki rewrite.

With htaccess, it works like a charm.

https://combostrap.com/admin/nice-url-noln5keo

**Comment by bpaddock** [comment]
No problem about the delay.

I'm using the Erlang web server YAWS, which does not support htaccess.

If dokuwiki rewrite can't be made to work, then please document that it doesn't.
I spent far to much time figuring out why it broke, because of the meaningless error messages that are generated by the browsers.

Thank you for the consideration.

**Comment by gerardnico** [comment]
htaccess is a misleading option name. 

It just means that the web server is configured to do the rewrite. I personally use Nginx.

See:
https://www.dokuwiki.org/rewrite#option_1web_server

**Comment by gerardnico** [comment]
I let it open to check and resolve this issue later as you proposed. 

I'm actually not in a really healthy state, hopefully, I can take a look quickly.

Best wishes

**Comment by gerardnico** [comment]
I have [[https://www.dokuwiki.org/plugin:combo#upgrade_steps|documented]] that it's not supported on the plugin page.
Is it enough ?

I checked to make it works but this is too much work.

I hope that you succeed with the web server rewrite.

All the best
Nico
