### ISSUE TITLE
Option to put sidebar at the top on mobile view

### ISSUE THREAD

**Issue by listerr** [ComboStrap/combo#56]
On the bootstrap3 template, and the default DW template, when the site is viewed on small / mobile screens, the
sidebar with the navigation collapses and is placed at the top of the page.

With Combo, the navigation disappears to the bottom of the page.

If the page has long content, it becomes awkward to navigate the site, because all the navigation has moved to the bottom of the page, having to scroll down to the end of the page every time.

For me, my site has a long introduction page and which prompts users to register. Users come back to the site, login, and register again even though they already have access (because they don't scroll down to the end of the first page to see the navigation that appears when they login.). Or, they just don't understand how to navigate the content beyond the first page!

Is it possible to have an option to make the sidebar behave like it does in bootstrap3 / DW template and collapse at the top?

This seems much better / intuitive navigation.

**Comment by gerardnico** [comment]
Yeah, I agree that we need to do better on templating.

As of today, I just mimic the bootstrap website and the navigation is just in the header bar.
Can you give me a visual example?

**Comment by listerr** [comment]
I'll see if I can recreate it on a test page and do some screenshots.

The problem is that the site has multiple levels of access for different types of user, so I use a few tricks with the ACL permissions and the ifauthex plugin so that when users are logged in, the sidebar only shows the navigation for the content they have access to, depending on what groups they are in.

Unfortunately ifauthex makes a mess of the top slot if I use it to add more options there.(It seems to wrap text in <p> tags which disturbs the alignment) But I use the sidebar and a combination of simplenavi/catlist plugins to display only the navigation for content they have access to and provide a usable navigation tree for the site which automatically updates when adding new documents etc.

All good on desktop, but on mobile, people don't see any noticeable difference after they login, because the "sidebar" is always shoved at the bottom of the page, and if the content is quite long, they don't see the navigation unless they scroll all the way down.

I made some modifications to the content to make some pages shorter, or add lots of "please scroll down to see the navigation" "important stuff you need to read is here" links at the top, rather than just logging in and "nothing has changed".

The "goto" plugin is also useful to direct users to the right page based on which group they are in, after they login.

So people sign up, login once, see nothing interesting and then never come back. Or they create multiple logins as it wasn't entirely clear to them, so they keep filling in the registration form instead of logging in every time they want to login.

This has been an epic lesson site design - what seems obvious on desktop isn't obvious on mobile, and also in making DokuWiki do some stuff it probably wasn't meant to do, but whatever!

It's a little fiddly: it's essentially a closed wiki with three levels of access.

Unauthenticated users see some basic info with an invitation to create a new login, or login if they're already registered.

They can then create a login and see slightly more information in the members area, but then have to fill in a form with the rest of their details before I can grant the relevant access.

(It's an association for an apartment block. Anyone who lives in the apartment block can register, but a legal requirement means we have to check the details and distinguish between people who rent their apartment and people who own their apartment before we can give the relevant access.)


Rob

*From: *Nickeau ***@***.***>
*To: *ComboStrap/combo ***@***.***>
*CC: *Rob Lister ***@***.***>; Author ***@***.***>
*Date: *20 Feb 2023 08:28:21
*Subject: *Re: [ComboStrap/combo] Option to put sidebar at the top on mobile view (Issue #56)

**Comment by gerardnico** [comment]
ifauthex creates p because it has the stack value (and not normal) for the p parameters. 
Line 70: https://github.com/mittelab/ifauthex-dokuwiki-plugin/blob/master/syntax.php

Authentication based workflow is always tricky.

Some people want to show what they can access if they login, other doesn't.

That's why I ask for a visual or a sequence diagram (if you have).

As of today, the default is to redirect to the requested page after they have logged.

**Comment by listerr** [comment]
Thanks for that re: ifauthex.  I've added an issue for that: https://github.com/mittelab/ifauthex-dokuwiki-plugin/issues/15

Seems to me that this is mostly a layout/navigation issue, which is made worse by my dynamic sidebars.

If you go to https://www.dokuwiki.org/ or any dokuwiki using the default or bootstrap3 template, you will see the sidebar
collapses to the **top** of the page when viewed on a narrow browser / mobile. 

This to me seems more intuitive than it "disappearing" to the bottom of the page. If the content is longer than the screen can display, then it's not obvious in some cases that you have to scroll down to get to the navigation.

**Comment by gerardnico** [comment]
Hi Robert,

I just copy the default template of bootstrap. 
Their last template put the sidebar in a ''off-canvas'' on mobile in the header bar.

It makes sense as navigation is an action.

**Comment by listerr** [comment]
Doesn't it currently use the off-canvas for the dokuwiki menus?

I don't think most users of the site would understand:

"When looking at this site on mobile, the all the navigation is now in the teeny tiny little thing I have to tap on the right."

Needs to be more obvious as people are unable to navigate my site and keep asking me questions that are already answered, then I paste them a link, but they can't seem to find stuff for themselves because the navigation is not right in front of their face.

**Comment by gerardnico** [comment]
From an historic point of view, I got also the same feedback but with the content.

Why do I need to scroll the navigation before seeing what's important the content ?

It seems that you have put navigational content in the sidebar. Why not in the main page ? (Without visual, I don't see really the problem, it's just a guess)

**Comment by gerardnico** [comment]
From a perspective in the future, I'm actually adding a real template engine (handlebar)

Design has its rule but as also its taste and colour.

**Comment by gerardnico** [comment]
https://github.com/ComboStrap/dokuwiki-template-strap/blob/main/main.php
Line 313: in place of order-last put order-first

**Comment by listerr** [comment]
> From an historic point of view, I got also the same feedback but with the content.
> 
> Why do I need to scroll the navigation before seeing what's important the content ?
> 
> It seems that you have put navigational content in the sidebar. Why not in the main page ? (Without visual, I don't see really the problem, it's just a guess)

I use a plugin, simplenavi in the sidebar to just automatically build the navigation. I was using combostrap's simplenavi as it looks a bit nicer, but it doesn't seem to respect the permissions where the user doesn't have access to things.

> https://github.com/ComboStrap/dokuwiki-template-strap/blob/main/main.php Line 313: in place of order-last put order-first

Interesting. I changed that and it moves to the top for smaller widths. Now I just need to find a way to make it toggle.

If you look at the [Bootstrap 5.0 docs](https://getbootstrap.com/docs/5.0/layout/breakpoints/), say:

At wider widths:

![image](https://user-images.githubusercontent.com/3037635/220442728-70c5fdd6-64cf-49dd-8eb2-2085880a62d6.png)

- Interestingly if the screen is not tall enough to display all the sidebar contents, then a scroll bar appears in the sidebar. Combostrap doesn't seem to do this.

- The navbar at the top is not sticky but scrolls off, but the second bar with "search docs" etc. stays visible. I'll have to see if I can replicate that in combostrap. The sticky/not sticky can be done. The next bit they call a "subnavbar".

At slightly narrower widths, the TOC shifts from the right, to the top of the page:

![image](https://user-images.githubusercontent.com/3037635/220444335-162f4628-2cc0-4d6b-a552-80d964b95418.png)

Then at narrow widths:

![bs5narrow](https://user-images.githubusercontent.com/3037635/220445116-97f6c27d-eac1-41de-983f-1bf097403dd2.gif)

- All the navi options disappear into the button on the right.
- The sidebar collapses into a button on the subnvai.

In Bootstrap 5.2, it changed again:

- The subnavi is gone completely.
- At narrower widths, they've swapped it around so the top navi collapses into the top right, and the sidebar collapses into the top left. The TOC appears in a drop-down toggle at the top of the page.

![bs52narrow](https://user-images.githubusercontent.com/3037635/220447141-e3cd6988-178f-46cc-a6b9-912b1cc064e6.gif)

This all looks very neat on mobile.

**Comment by gerardnico** [comment]
The last release has a default theme that puts the sidebar on top :)

This is a really big release, so there is some manual change mandatory.
https://combostrap.com/release/release-1-25-layout-all-the-way-l17jxp17

All the best
