### ISSUE TITLE
page-explorer periodically stops working

### ISSUE THREAD

**Issue by DeliriumCode** [ComboStrap/combo#58]
After a clicking on maybe the third or so page link generated from the page-explorer control, all the page explorer links disappear
Clearing the cache sometimes causes it to come back.

I have a basic wiki setup with the following sidebar:
```
<bar background-color="gradient-light" color="secondary" line-spacing="md">
<btn width="fit">
[[getting_started]]
</btn>

**Support Groups**
<page-explorer tree line-spacing="xs" ns="support_groups:"></page-explorer>
**Social Groups**
<page-explorer tree line-spacing="xs" ns="social_groups:"></page-explorer>
**Crisis**
<page-explorer tree line-spacing="xs" ns="crisis:"></page-explorer>
**Events** 
<page-explorer tree line-spacing="xs" ns="events:"></page-explorer>
**Medical**
<page-explorer tree line-spacing="xs" ns="medical:"></page-explorer>
**Services**
<page-explorer tree line-spacing="xs" ns="Services:"></page-explorer>
**Organisations**
<page-explorer tree line-spacing="xs" ns="organisations:"></page-explorer>
**User Content**
<page-explorer tree line-spacing="xs" ns="user_content:"></page-explorer>
**Wiki** 
<page-explorer tree line-spacing="xs" ns="wiki:"></page-explorer>
</bar>
```

**Comment by DeliriumCode** [comment]
This looks like it was caused by not having a preceding : in the ns=
i.e.
Changing
`<page-explorer tree line-spacing="xs" ns="support_groups:"></page-explorer>`
to
`<page-explorer tree line-spacing="xs" ns=":support_groups:"></page-explorer>`
Resolves this issue...

**Comment by DeliriumCode** [comment]
.

**Comment by gerardnico** [comment]
Thanks for reporting.

The `ns` attribute takes the default value of the requested page. I added it for documentation purpose.

If you use the same sidebar, you just need to create one at the root with:
```
<page-explorer tree line-spacing="xs" ></page-explorer>
```

I check the bug.

**Comment by DeliriumCode** [comment]
So i wanted control over the order. I also wanted the sidebar to be the same on all pages rather than just the current namespace.

The final site is transliverpool.com

**Comment by gerardnico** [comment]
Ah ok ... I get it. Nice!

**Comment by gerardnico** [comment]
I try to reproduce your error but I couldn't figure it out. I have added a guard so that it will not happen again. Thanks for trace. Really helpful and all the best with your publication.

**Comment by DeliriumCode** [comment]
So i think it is linked to when the cache of the page-explorer is generated and the current page.

If you turn off caching, it works on the root page but not the child pages as i wasn't putting a : before the ns part.

so user navigates to site, it all works. If the cache gets invalidated, its regenerated based off the current page.

**Comment by gerardnico** [comment]
Caching is a bad beast. Thanks for the feedback. I will look at it.
