### ISSUE TITLE
Error when used with dokuwiki sqlite plugin 2023-06-21

### ISSUE THREAD

**Issue by robertoea** [ComboStrap/combo#68]
``Error: Call to undefined method dokuwikilpluginIsqlite\SQLiteDB::create_function()``

Probably a side effect of its recent refactorings.

**Comment by gerardnico** [comment]
Main ... you are talking about [the June release](https://www.dokuwiki.org/plugin:sqlite#changes_from_earlier_releases).
Still, a fact that you can't rely on other plugins as there is no version defined.
Thanks for reporting., I'll check it out.

**Comment by gerardnico** [comment]
I have made the needed modifications and tested it on our server. 
The last modification was a migration error.
It works and passes all tests.
Thanks again for the report.

**Comment by Klap-in** [comment]
> Main ... you are talking about [the June release](https://www.dokuwiki.org/plugin:sqlite#changes_from_earlier_releases).
> Still, a fact that you can't rely on other plugins as there is no version defined.
> Thanks for reporting., I'll check it out.

I guess that for a lot of plugins this is extra overhead as updating release dates (in code and wiki) is already a mess. I guess that this is now the main reason for not having version numbers for plugins, and probably that it  has grown so historically? But especially for plugins that are a dependency for other plugins, it is in my view relevant to consider this. You might consider opening an issue in the DokuWiki’s issue tracker with a proposal?

**Comment by gerardnico** [comment]
> You might consider opening an issue in the DokuWiki’s issue tracker with a proposal

Thanks @Klap-in . I'm pretty sure that they are well aware of this problem and that they don't care as the forum is full of this kind of problem. A quick update, php way and that's done.
