### ISSUE TITLE
Metadata Manager suddenly stopped working

### ISSUE THREAD

**Issue by robbertdam** [ComboStrap/combo#78]
In my installation, the menu items Metadata Manager and Cache Menu stopped working.

I see the following message when clicking on Metadata Manager from the menu:

`Action unknown: metamanagermenuitem`

Similar for the Cache Menu:

`Action unknown: cachemenuitem`

I've tried to:

- update to latest ComboStrap
- disable all other plugins
- revert to default ComboStrap config (clearing local.php file)

...but it still does not work.

**Comment by gerardnico** [comment]
Sorry for that.

See this previous discussion on why it happens.
https://github.com/ComboStrap/combo/discussions/74

**Comment by gerardnico** [comment]
If there is any problem, you should see the problems in the log of php or your http webserver.

**Comment by gerardnico** [comment]
Wouah. I would have never found it. Thanks.
