### ISSUE TITLE
Syntax highlighting for bash as file with line numbers overlays prompt with line numbers

### ISSUE THREAD

**Issue by knieselpriem** [ComboStrap/combo#82]
If a `file` block is defined for syntax highlighting `bash` with line numbers, then the prompt overlays with the line numbers. 

Example (just for showing the issue, though it's not bash code):
```
<code bash>nano /etc/sysctl.d/99-sysctl.conf</code>
<file bash "99-sysctl.conf" line-numbers="true" data-start="123">
# disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
</file>
``` 
![grafik](https://github.com/ComboStrap/combo/assets/13505501/a61caffa-97d8-410f-970a-d942ceb8412e)

**Comment by knieselpriem** [comment]
I tried this already:
- empty the configuration field for `bash` default prompt: then the default prompt `user@machine` is generated
- extra attribute `prompt=""`, then the prompt `""` is shown
- extra attribute `prompt=`, then the prompt `true` is shown

How can I disable the default prompt?

**Comment by gerardnico** [comment]
Bug then here (for me)
https://github.com/ComboStrap/combo/blob/main/ComboStrap/Prism.php#L295

You may be can set an empty string in the configuration but I’m not sure that it will work.
https://combostrap.com/utility/combostrap-prism-qgu0x6gx#prompt

**Comment by knieselpriem** [comment]
An empty string or a blank ` ` results in the prompt `true`.

**Comment by gerardnico** [comment]
Yes. Sorry. Put that aside. ETA next week. Monday or Tuesday.

**Comment by gerardnico** [comment]
The prompt may be now empty and the line numbers rendering win over prompt rendering.

**Comment by gerardnico** [comment]
You need to update it via URL
https://combostrap.com/release/how-to-update-combo-or-a-third-party-plugin-in65c0ya#how_to_update_the_combo_plugin

I'll wait for your feedback. 
Have a nice day.

**Comment by knieselpriem** [comment]
Well done!
