### ISSUE TITLE
Feature request: highlight lines in file block

### ISSUE THREAD

**Issue by knieselpriem** [ComboStrap/combo#83]
It would be nice to highlight line within `file` blocks, like e.g. `sxh` does.

Example (sxh code highlighter):
```
<sxh; title: just-an-example.txt; highlight: [3-5]>
line 1
line 2
line 3
line 4
line 5
line 6
line 7
</sxh>
```
![grafik](https://github.com/ComboStrap/combo/assets/13505501/39e939a5-9bf9-477a-afae-5b44cb85c226)

**Comment by gerardnico** [comment]
The engine is prism.

I found this plugin 
https://prismjs.com/plugins/line-highlight/

Is it what you expect to be implemented?

**Comment by knieselpriem** [comment]
I found nothing in the documentation of combostrap or DokuWiki, how to install a `prism` plugin.

Can you give a hint?

**Comment by gerardnico** [comment]
It’s already included by Combostrap. I need to add this plugin to our prism component.

You could add it yourself but that’s not easy as 1,2,3

**Comment by gerardnico** [comment]
Done.

Steps: 
* Update before testing:
https://combostrap.com/release/how-to-update-combo-or-a-third-party-plugin-in65c0ya#how_to_update_the_combo_plugin
* Test: Doc
https://combostrap.com/utility/combostrap-prism-qgu0x6gx#line_highlight

Is it ok ?

**Comment by knieselpriem** [comment]
Well done!
