### ISSUE TITLE
data-page-id CSS selectors

### ISSUE THREAD

**Issue by vaniwiki** [ComboStrap/combo#86]
Not sure how to sell this feature, but I used to put this code into my `<body>` tag: `data-page-id="<?php echo $ID ?>`, which makes it possible to style one's website according to section, targeting a specific namespace or page.

For more info, see [this forum thread](https://forum.dokuwiki.org/d/18190-css-selector-for-namespace).

**Comment by gerardnico** [comment]
This is already in it. If you inspect any link you get a `data-wiki-id`:

```html
<a data-wiki-id="howto:getting_started:1_dokuwiki">How to install Dokuwiki ?</a>
```

**Comment by vaniwiki** [comment]
I don't mean links. I want to style all pages inside a certain namespace. In one example, I want the namespace "letters" to show me all text in a monospaced font. So I would add this to my css: `body[data-page-id^="letters:"]` and style it.

In another hypothetical example, I could style all pages starting with "blog:01:" (for January) with a snowy background.

I'm sure I can give other practical examples as well. I've used it to style certain books in a certain way, or make blockquotes in one section looks different from another section.

**Comment by gerardnico** [comment]
On a design level, one domain, one design is the recommendation.

As of today, you can apply a template to one namespace.
https://combostrap.com/theme/what-is-a-template-z9tl87hg

**Comment by gerardnico** [comment]
The explanation is here:
https://combostrap.com/howto/how-to-create-your-own-theme-m092ki81#how_to_apply_a_template_for_a_whole_namespace

**Comment by vaniwiki** [comment]
I have been going through the ComboStrap directories now to figure out how I can just paste my code into the body tag. But that did not work as expected. What was previously simple (in Bootie, just edit main.php, if I'm not mistaken), now it requires to make themes per each...

If one reason why people want to apply a template to a namespace is that they want to style it differently, wouldn't it make much more sense to just include a tiny data-page-id snippet into the body tag? But let's say that I want to do this myself, how do I go about to add this php snippet in the .hbs file?
