### ISSUE TITLE
Related component to show pages limited to namespace

### ISSUE THREAD

**Issue by vaniwiki** [ComboStrap/combo#88]
Similar to the Backlinks plugin, with its syntax:

```
{{backlinks>.#include}}
{{backlinks>.#!exclude}}
```

In my case, I have many lecture transcripts that link to specific pages and verses. On these pages it would be helpful to show links to the lectures namespace, but exclude links from the synonyms namespace...

**Comment by gerardnico** [comment]
This is already present with page sql.
https://combostrap.com/navigation/backlinks-management-in-combostrap-4p2ow8zm#page_sql

You just need to apply your own filter or logic.

**Comment by vaniwiki** [comment]
Oh, great! I'm not a database person, which is why I'm using DokuWiki, but I'll try to figure this out. Thanks! :)
