### ISSUE TITLE
Missing links return relative links

### ISSUE THREAD

**Issue by vaniwiki** [ComboStrap/combo#97]
I have many missing links in my content, due to naming conventions. But previously the missing (red) links would all go to their correct content, based on a redirect list that I compiled. Although I want to make all the links work, that will take me some time, and meanwhile I am very happy if the red links all point to the right place.

Demo wiki test [here](https://demo.combostrap.com/redlink/test_page).

**Comment by gerardnico** [comment]
You got a relative link and an absolute link. They are pointing to the same page because your are not on the root therefore they point to different pages.

**Comment by gerardnico** [comment]
I have created the absolute page and you can see that the 2 links points to the same page.

This is to mirror the weird dokuwiki handling of relative link.

If the page does not exist, the relative link point to a relative page.

**Comment by gerardnico** [comment]
It's not an issue for combostrap. This is the way it works when you want to create relatief pages.
